- hosts: localhost
  name: ONTAP
  gather_facts: false
  vars:
    state: present
  tasks:
  - name: "{{ tower_job_template_name }}"
    netapp.ontap.na_ontap_volume:
      state: "{{ state }}"
      name: "{{ volname }}"
      aggregate_name: "{{ aggrname }}"
      size: "{{ size }}"
      size_unit: gb
      export_policy: "{{ export_policy }}"
      junction_path: "{{ '' if not export_policy else '/' + volname }}"
      space_guarantee: "none"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      use_rest: auto
      validate_certs: false
